### ISSUE TITLE
Replace gets() with fgets() in graders

### ISSUE THREAD

**Issue by CatalinFrancu** [varena/infoarena#27]
The tasks [alegere](http://varena.ro/problema/alegere), [cub](http://varena.ro/problema/cub), [dictionar](http://varena.ro/problema/dictionar), [divimax](http://varena.ro/problema/divimax), [jimjam](http://varena.ro/problema/jimjam) and [sir](http://varena.ro/problema/sir) have graders that use `gets()`.

On the new system gcc/g++ are invoked with `-std=c++14`, which causes it not to expose the `gets()` definition, so the graders don't compile.

- [ ] Fix the graders, probably by replacing `gets()` with `fgets()`. Remember that `gets()` discards the final `\n`, while `fgets()` includes it.
- [ ] Reevaluate jobs for these tasks submitted on or after January 5, 2021. So far only Cub has some.

**Comment by teodorplop** [comment]
Everything should be fine now. Thanks for notifying me.
